import Navbar from "@/Components/Navbar/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="max-w-screen-xl mx-auto font-inter antialiased">
       <Navbar></Navbar>
          <div>
            {children}
          </div>
          {/* <Footer></Footer>  */}
      </body>
    </html>
  );
}
